//
// Generated file, do not edit! Created by opp_msgtool 6.1 from RoutingMessage.msg.
//

#ifndef __ROUTINGMESSAGE_M_H
#define __ROUTINGMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class RoutingMessage;
/**
 * Class generated from <tt>RoutingMessage.msg:16</tt> by opp_msgtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet RoutingMessage
 * {
 *     string origin;
 *     int seq;
 *     string type;   // "RIP" or "AHRP"
 *     string payload;
 *     string signature;
 * }
 * </pre>
 */
class RoutingMessage : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string origin;
    int seq = 0;
    omnetpp::opp_string type;
    omnetpp::opp_string payload;
    omnetpp::opp_string signature;

  private:
    void copy(const RoutingMessage& other);

  protected:
    bool operator==(const RoutingMessage&) = delete;

  public:
    RoutingMessage(const char *name=nullptr, short kind=0);
    RoutingMessage(const RoutingMessage& other);
    virtual ~RoutingMessage();
    RoutingMessage& operator=(const RoutingMessage& other);
    virtual RoutingMessage *dup() const override {return new RoutingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getOrigin() const;
    virtual void setOrigin(const char * origin);

    virtual int getSeq() const;
    virtual void setSeq(int seq);

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual const char * getSignature() const;
    virtual void setSignature(const char * signature);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RoutingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RoutingMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline RoutingMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<RoutingMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __ROUTINGMESSAGE_M_H

